### ISSUE TITLE
ambient_light broken in 0.4.2

### ISSUE THREAD

**Issue by brodieG** [tylermorganwall/rayrender#10]
I believe commit 21d87e6 broke rendering of scenes illuminated only by ambient light.  This kinda makes sense looking at the diff since the change was to add an exit AFAICT before the `ambient_light` parameter is considered.

I noticed this trying to run the following example from `?render_scene`:

```
scene = generate_ground(depth=-0.5, material = diffuse(color="white", checkercolor="darkgreen"))

render_scene(scene,parallel=TRUE,samples=500)
```

This worked as expected as late as 21b57f0.

**Comment by tylermorganwall** [comment]
Fixed in d10b255bd33289f68f20b9de96883b8388ab5cee
