### ISSUE TITLE
Renders only black image

### ISSUE THREAD

**Issue by vonjd** [tylermorganwall/rayrender#14]
No matter which code I use from the documentation, it only renders a black image?!?

Example:

```
library(rayrender)
#Generate the ground and add some objects
scene = generate_ground() %>%
  add_object(sphere(material = diffuse(color="#ff5555")))
render_scene(scene, parallel = TRUE, width = 800, height = 800, samples = 1000)
```

Any thoughts?
Thank you!

**Comment by trevorld** [comment]
Are you using the ``release`` version on CRAN or the development version on Github installable by ``remotes::install_github("tylermorganwall/rayrender")``?

I suspect you are affected by #10 which has been fixed in the development version but the fix hasn't yet been released to CRAN.

**Comment by tylermorganwall** [comment]
Yes, try updating to the latest version on github and see if that fixes your issue.

```r
remotes::install_github("tylermorganwall/rayrender")
```

**Comment by vonjd** [comment]
Yes, it does fix it... thank you!

When will you update the CRAN version?

**Comment by tylermorganwall** [comment]
The latest version has just been released on CRAN.

**Comment by vonjd** [comment]
Works like a charm... thank you!
