### ISSUE TITLE
render_scene no longer runs in parallel

### ISSUE THREAD

**Issue by tteo** [tylermorganwall/rayrender#16]
Hi Tyler, I've been puzzled by why rendering jobs have slowed down rather drastically. Windows task manager shows that render_scene is only using one thread.  Set `options(cores= 12)`, but still only one thread at load. `render_highquality()` in rayshader is also painfully slow. 

This used to work—had all 24 threads running at close to 100%. Tried 3.6.3 and 4.0.0, RStudio stable and preview, no luck. Tested multi-threaded performance with Geekbench, works fine.

Any ideas?

**Comment by tylermorganwall** [comment]
Is this still an issue?

**Comment by tteo** [comment]
I updated rgl and it's no longer an issue. Thanks, Tyler!

**Comment by tylermorganwall** [comment]
Great!
