### ISSUE TITLE
single_sample.h

### ISSUE THREAD

**Issue by define-private-public** [tylermorganwall/rayrender#23]
https://github.com/tylermorganwall/rayrender/blob/86c49e367df18a673673188391a926443d177977/src/sampler.h#L7

It's referenced in that line, but I can't find it in the repo.  Where does it come from?

**Comment by tylermorganwall** [comment]
That comes from including the headers in the spacefillr package during compilation:

https://github.com/tylermorganwall/spacefillr

You can find the headers in the inst/include directory.
