### ISSUE TITLE
Start tagging your releases in git

### ISSUE THREAD

**Issue by define-private-public** [tylermorganwall/rayrender#24]
This is super-duper useful.  In fact, a lot of package managers sometimes use tags on commits to mark versions/releases:
https://git-scm.com/book/en/v2/Git-Basics-Tagging

I'd recommend you make an annotated tag via `git tag -a v0.21.6` on your most recent commit.  Then you need to do a `git push --tags`.  You should also then see "Releases" on this repo have one entry in them.

**Comment by tylermorganwall** [comment]
I've started added tags with the latest release
