### ISSUE TITLE
How to reduce dither?

### ISSUE THREAD

**Issue by jbum** [tylermorganwall/rayrender#27]
I'm new to R, and running this on a fresh install on a Mac in RStudio. When I render the first example under Usage in the README.

```
render_scene(scene, parallel = TRUE, width = 800, height = 800, samples = 1000)
```

I'm seeing heavy dithering, as compared to the illustration shown in the README.  Increasing samples doesn't seem to improve it much (I went as high as 1m). Is there a way to reduce the dithering?  My result shown below:

![rplot_1000](https://user-images.githubusercontent.com/287977/134749990-44a7d89a-7776-41cc-8f0e-993df897729b.png)

If there's an easy fix, consider mentioning it in the README?

UPDATE: I can get a bit closer to the illustrations by tripling or quadrupling the resolution (e.g. width=3200 height=3200, samples=1000) and resizing back to 800 in photoshop. Are the images in the README using oversampling?

**Comment by tylermorganwall** [comment]
By default, the scene is rendered with adaptive sampling: try setting `min_variance = 0` in `render_scene()`. That will turn off adaptive sampling and you should have much less noisy renders. 

Additionally, if you use less than or equal to 256 samples, use `sample_method = "sobol_blue"`; if you use more than 256 samples, use `sample_method = "sobol"`.

**Comment by jbum** [comment]
Much better thank you!

With min_variance = 0

```
> system.time(render_scene(scene, parallel = TRUE, width = 800, height = 800, samples = 1000, clamp_value=10, min_variance=0))
   user  system elapsed                                               
957.984  14.364 163.666 
```
![rplot_1000_mv0](https://user-images.githubusercontent.com/287977/134753218-486b606a-71c7-4e05-9d23-41e06f0e2559.png)

**Comment by tylermorganwall** [comment]
Great!

**Comment by jbum** [comment]
width=3200 height=3200 (without min_variance=0) looks even nicer, but if I combine it with min_variance=0 (and sobol), I ran out of memory. :-)

![rplot_3200_1k_downsampled](https://user-images.githubusercontent.com/287977/134754820-bb918263-3613-4060-b5e3-71205d766a1b.png)
