### ISSUE TITLE
r-rayrender on conda-forge?

### ISSUE THREAD

**Issue by rsignell-usgs** [tylermorganwall/rayrender#28]
Are there plans to release `r-rayrender` on conda-forge or are there issues with that?

I ask because that looks like the one package that is preventing us from conda installing an environment that would run
https://github.com/OpenTopography/Jupyter/blob/main/OT_02_RayShader.ipynb

cc: @dmasaki

**Comment by tylermorganwall** [comment]
I personally am not going to do this due to time and lack of involvement/expertise with conda-forge, but if someone else felt the desire to maintain this I would be open to that type of collaboration.
