### ISSUE TITLE
Can't fload - error

### ISSUE THREAD

**Issue by tombroekel** [tylermorganwall/rayrender#33]
Hi,
I can't get render_highquality() to work, as the following error occurs. I use the latest github version of rayrender. I run R through R-Studio:

R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: OS X  12.3.1

<img width="1124" alt="Screenshot 2022-04-14 at 23 26 21" src="https://user-images.githubusercontent.com/53934903/163479700-dd7c03ac-8e68-473e-b1b7-c9ada3158c28.png">

**Comment by tylermorganwall** [comment]
This is a closed rayshader issue (https://github.com/tylermorganwall/rayshader/issues/216) —solve it by updating to the latest version of rayshader on github.

```r
remotes::install_github("tylermorganwall/rayshader")
```
