### ISSUE TITLE
Not sure how to handle this error

### ISSUE THREAD

**Issue by RobinKohrs** [tylermorganwall/rayrender#34]
I tried to follow the spectecular example [here](https://twitter.com/researchremora/status/1418392590244892673/photo/2). 
In the end I call: 

```
render_highquality(out_file, samples=100, width=1000, height=1000)
```

However, I always (in the cases my R-Studio does not abort before) get this error: 

```
Error in render_scene_rcpp(camera_info = camera_info, scene_info = scene_info) : 
  Could not find /tmp/RtmpGxag9h//tmp/RtmpGxag9h/temprayfile.png
```
Maybe this is a really silly question (and in case it is I am really sorry), but I did not find any help online so far:) 
In any case, thanks so much for these incredible packages !!!

**Comment by tylermorganwall** [comment]
Whatever caused this, it is unlikely to happen with the latest version. Feel free to post in this issue if this problem is still occurring.
