### ISSUE TITLE
Any plans for a CRAN release?

### ISSUE THREAD

**Issue by javierluraschi** [tylermorganwall/rayrender#4]
I'm sure I'm not the only one excited for this! :)

**Comment by tylermorganwall** [comment]
Yep! Just wanted to finish implementing an optimized BVH algorithm so scenes using the new .obj support would render faster. Lots of cool new features in the latest version (and should be fully CRAN compliant, which can be a challenge)

**Comment by tylermorganwall** [comment]
Closed! 

https://cran.r-project.org/web/packages/rayrender/index.html
