### ISSUE TITLE
cant install rayrender via github

### ISSUE THREAD

**Issue by nahardito** [tylermorganwall/rayrender#42]
im newbie in r

i have followed instructions to install rayrender via "remotes::install_github("https://github.com/tylermorganwall/rayrender")"  but an error. There are some errors likes "problem copying .\tylermorganwall-rayrender-f542630\tests\testthat\_snaps\basic-rendering\render_camera_info_test12_lookfrom-c(-10, 1, 10)_lookat-c(0, 0.75, 0)_camera_up-c(0, 1, 0)_focal_distance-5_fov-0.png to..." and the last line likes:
"copying to build directory failed
Error: Failed to install 'rayshader' from GitHub:
Failed to install 'rayrender' from GitHub:
! System command 'Rcmd.exe' failed"

Whats the solution bout that? because when i tried before 12 feb, success. And i see there is an update on 12 feb, does have any affect?
Thanks

**Comment by tylermorganwall** [comment]
This sounds like a local configuration issue--I can't provide any assistance.
