### ISSUE TITLE
render_highquality error on matrix with na values

### ISSUE THREAD

**Issue by LTHD97** [tylermorganwall/rayrender#49]
Hi Tyler,
Thx for your work, project is very cool, using it for a few days trying to render data with 3D through rayshader
> packageVersion("rayshader")
[1] ‘0.36.1’
> packageVersion("rayrender")
[1] ‘0.30.3’
Was followings some tutorial wich were not working at some points. Seems that's its related to render_highquality generating error when matrix use in plot3D has NA values (render_snapshot is working fine). error : Erreur dans rayvertex::validate_mesh(mesh) : 
  !any(is.na(normals)) n'est pas TRUE
Hace a nice day, thx again

**Comment by trevorld** [comment]
Could you please provide a [minimal, reproducible example](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) of your issue?  What was the tutorial?

**Comment by LTHD97** [comment]
Hi, was following this one
https://www.youtube.com/watch?v=zgFXVhmKNbU
code is here
https://github.com/Pecners/kontur_rayshader_tutorial/blob/main/main.R

not functionnal until i add "mat[is.na(mat)] <- 0" line 79

Have a nice day

**Comment by tylermorganwall** [comment]
This is referring to rayshader, not rayrender. If this is still an issue, it should be opened on that repo instead.
